name: Update documentation
on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '**/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  generate:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Set environment
        shell: bash
        run: echo "::set-env name=VERSION::$( echo ${GITHUB_REF:10})"
      - name: Set document
        run: go get -u github.com/sai-lab/go-template@$VERSION
        env:
          GOPROXY: https://proxy.golang.org
          GO111MODULE: on
